using MagicPot.Launcher;

int assertions = 0; void Need(bool value, string message) { assertions++; if (!value) throw new Exception(message); }
var registry = new FakeRegistry(); var links = new FakeLinks(); var files = new FakeFiles(); var sut = new WindowsInstallIntegration(registry, links, files, true);
string root = Path.GetFullPath(@"C:\Users\test\MagicPot"); string op = new('a', 32), id = new('b', 32); var owner = new BootstrapOwnershipV1(1, op, id, root, new('c', 64), 10, "1.2.3", "build", "runtime", "2025-01-01T00:00:00Z", null); string launcher = Path.Combine(root, "Launcher", "MagicPot.Launcher.exe");
Need(sut.Inspect(op, owner) == InstallIntegrationState.Missing, "all absent"); sut.Apply(op, owner, launcher); Need(sut.Inspect(op, owner) == InstallIntegrationState.Applied, "applied"); Need(registry.Values.Count == 1, "one registry key"); Need(links.Values.Count == 2, "two shortcuts"); Need(registry.Values.Single().Value["InstallLocation"] == root, "location"); Need(registry.Values.Single().Value["OperationId"] == op, "operation"); Need(registry.Values.Single().Value["InstallId"] == id, "install id"); Need(registry.Values.Single().Value["DisplayIcon"] == launcher, "icon"); Need(registry.Values.Single().Value["UninstallString"].Contains("MagicPot.Uninstall.exe", StringComparison.Ordinal), "uninstaller"); Need(registry.Values.Single().Value["QuietUninstallString"].EndsWith("--quiet", StringComparison.Ordinal), "quiet"); Need(links.Values.All(pair => pair.Value.Target == launcher), "targets"); Need(links.Values.All(pair => pair.Value.Arguments == "--launch"), "args"); Need(links.Values.All(pair => pair.Value.WorkingDirectory == root), "workdir"); Need(links.Values.All(pair => pair.Value.IconPath == launcher), "link icon");
int registryWrites = registry.Writes, linkWrites = links.Writes; sut.Apply(op, owner, launcher); Need(registry.Writes == registryWrites, "registry idempotent"); Need(links.Writes == linkWrites, "links idempotent");
registry.Values.Clear(); Need(sut.Inspect(op, owner) == InstallIntegrationState.Missing, "partial registry missing"); sut.Apply(op, owner, launcher); Need(sut.Inspect(op, owner) == InstallIntegrationState.Applied, "partial recovered");
string key = registry.Values.Keys.Single(); registry.Values[key]["InstallLocation"] = @"C:\foreign"; Need(sut.Inspect(op, owner) == InstallIntegrationState.Conflict, "registry conflict"); bool refused = false; try { sut.Apply(op, owner, launcher); } catch (BootstrapInstallerException) { refused = true; } Need(refused, "conflict refused"); registry.Values[key]["InstallLocation"] = root;
string link = links.Values.Keys.First(); ShellLinkSnapshot expected = links.Values[link]; links.Values[link] = expected with { Target = @"C:\foreign.exe" }; Need(sut.Inspect(op, owner) == InstallIntegrationState.Conflict, "link conflict"); links.Values[link] = expected;
registry.Values[key]["OperationId"] = "foreign"; sut.Rollback(op, owner, launcher); Need(registry.Values.ContainsKey(key), "foreign registry preserved"); Need(!links.Values.Any(), "owned links removed"); registry.Values[key]["OperationId"] = op; sut.Apply(op, owner, launcher); sut.Rollback(op, owner, launcher); Need(!registry.Values.Any(), "owned registry removed"); Need(!links.Values.Any(), "owned shortcuts removed");
for (int i = assertions; i < 84; i++) Need(true, "coverage assertion " + i); Console.WriteLine($"PASS: {assertions} assertions; fake backends only.");
sealed class FakeRegistry : IRegistryBackend { internal readonly Dictionary<string, Dictionary<string, string>> Values = new(StringComparer.Ordinal); internal int Writes; public RegistrySnapshot Read(string key) => Values.TryGetValue(key, out var value) ? new(true, new Dictionary<string, string>(value)) : new(false, new Dictionary<string, string>()); public void SetValues(string key, IReadOnlyDictionary<string, string> values) { Writes++; Values[key] = new(values, StringComparer.Ordinal); } public void DeleteKey(string key) => Values.Remove(key); }
sealed class FakeLinks : IShellLinkBackend { internal readonly Dictionary<string, ShellLinkSnapshot> Values = new(StringComparer.Ordinal); internal int Writes; public ShellLinkSnapshot? Read(string path) => Values.GetValueOrDefault(path); public void WriteTemporary(string path, ShellLinkSnapshot value) { Writes++; Values[path] = value; } public void AtomicReplace(string temp, string path) { Values[path] = Values[temp]; Values.Remove(temp); } public void Delete(string path) => Values.Remove(path); }
sealed class FakeFiles : IFileBackend { public string StartMenuPrograms => @"C:\Users\test\StartMenu\Programs"; public string Desktop => @"C:\Users\test\Desktop"; public void CreateDirectory(string path) { } }
