import test from 'node:test'
import assert from 'node:assert/strict'
import { csString, generateSource, validateConfiguration } from './generate-update-config.mjs'
const zeroKey = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
const valid = () => ({ schema: 1, launcherVersion: '1.2.3', channels: { stable: 'https://example.test/owner/repo/releases/download/stable/channel.json', beta: 'https://example.test/owner/repo/releases/tag/beta', nightly: 'https://example.test/owner/repo/releases/download/nightly/channel.json' }, trustedSources: [{ origin: 'https://example.test', repoPathPrefix: '/owner/repo' }], publicKeys: { 'test-key': zeroKey }, bootstrapPublicKeys: { 'bootstrap-key': zeroKey } })
const rejects = (mutate, pattern) => { const value = valid(); mutate(value); assert.throws(() => validateConfiguration(value, '1.2.3'), pattern) }
test('disabled output is deterministic', () => { const a = generateSource(null); assert.equal(a, generateSource(null)); assert.ok(!a.includes('\r')); assert.match(a, /Create\(\).*Disabled/) })
test('valid configuration emits only compiled public data', () => { const source = generateSource(validateConfiguration(valid(), '1.2.3')); assert.match(source, /1\.2\.3/); assert.match(source, /new byte\[\]/); assert.match(source, /https:\/\/example\.test/); assert.doesNotMatch(source, /AAAAAAAA/) })
test('unknown and recursively forbidden fields are rejected', () => { rejects(v => { v.extra = 1 }, /unknown/); rejects(v => { v.channels = { ...v.channels, nestedSecret: 'x' } }, /forbidden/) })
test('bad URL and source are rejected', () => { rejects(v => { v.channels.stable = 'http://example.test/x' }, /HTTPS/); rejects(v => { v.channels.stable = 'https://u:p@example.test/owner/repo/releases/tag/x' }, /credential/); rejects(v => { v.trustedSources[0].origin = 'https://example.test/path' }, /origin/); rejects(v => { v.trustedSources[0].repoPathPrefix = '/owner/repo/releases' }, /repository/) })
test('missing bootstrap keys and invalid keys in either group are rejected', () => { rejects(v => { delete v.bootstrapPublicKeys }, /missing/); rejects(v => { v.publicKeys = { 'bad key': zeroKey } }, /key id/); rejects(v => { v.bootstrapPublicKeys = { 'bad key': zeroKey } }, /key id/); rejects(v => { v.publicKeys = { key: '***=' } }, /base64/); rejects(v => { v.bootstrapPublicKeys = { key: Buffer.alloc(31).toString('base64') } }, /base64|32 bytes/) })
test('key groups validate deterministically while update source emits manifest trust only', () => { const a = valid(); a.publicKeys = { z: zeroKey, a: zeroKey }; a.bootstrapPublicKeys = { y: zeroKey, b: zeroKey }; const first = generateSource(validateConfiguration(a, '1.2.3')); const second = generateSource(validateConfiguration({ ...a, publicKeys: { a: zeroKey, z: zeroKey }, bootstrapPublicKeys: { b: zeroKey, y: zeroKey } }, '1.2.3')); assert.equal(first, second); assert.doesNotMatch(first, /CompiledBootstrapTrustConfiguration|CreateCompiled/) })
test('channel must match trusted release source', () => rejects(v => { v.channels.beta = 'https://other.test/owner/repo/releases/tag/beta' }, /trusted source/))
test('C# strings escape quotes, slashes and controls', () => { assert.equal(csString('a"b\\c\n\t'), '"a\\"b\\\\c\\n\\t"'); const value = valid(); value.channels.stable = 'https://example.test/owner/repo/releases/download/x/a%22b.json'; const source = generateSource(validateConfiguration(value, '1.2.3')); assert.match(source, /a%22b\.json/); assert.ok(!source.includes('\r')) })
