import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { closeSync, linkSync, mkdirSync, mkdtempSync, openSync, readFileSync, readdirSync, renameSync, rmSync, symlinkSync, unlinkSync, writeFileSync, writeSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { pathToFileURL } from 'node:url'
import * as yauzl from 'yauzl'
import { installSafeDeleteTestDelegate, resetSafeDeleteTestHooks } from './test-safe-delete.mjs'
installSafeDeleteTestDelegate()
test.afterEach(resetSafeDeleteTestHooks)
const pack = await import(pathToFileURL(join(process.cwd(), 'scripts/launcher-dotnet/pack-release-artifact.ts')).href)
const SHA = 'abcdef0123456789abcdef0123456789abcdef01', CREATED = '2026-01-02T03:04:06Z'
function fixture(kind = 'app') { const root = mkdtempSync(join(tmpdir(), 'magicpot-pack-')), input = join(root, 'input'), output = join(root, 'out.zip'), identity = join(root, 'identity.json'); mkdirSync(input); const value = kind === 'app' ? { version: '1.2.3', buildId: '20260102-030406-abcdef0', commitSha: SHA, runtimeId: 'runtime-1', platform: 'win32', arch: 'x64', entrypoint: 'MagicPot.exe', createdAt: CREATED } : { runtimeId: 'runtime-1', platform: 'win32', arch: 'x64', pythonEntrypoint: 'python.exe', comfyuiEntrypoint: 'ComfyUI/main.py', createdAt: CREATED }; if (kind === 'app') writeFileSync(join(input, 'MagicPot.exe'), 'app'); else { writeFileSync(join(input, 'python.exe'), 'python'); mkdirSync(join(input, 'ComfyUI')); writeFileSync(join(input, 'ComfyUI/main.py'), 'print(1)') } writeFileSync(identity, JSON.stringify(value)); return { root, input, output, identity, value, args: ['--kind', kind, '--input-dir', input, '--output', output, '--identity', identity] } }
async function manifest(path) { const zip = await yauzl.openPromise(path, { lazyEntries: true }); try { for await (const entry of zip.eachEntry()) if (entry.fileName === 'manifest.json') { const stream = await zip.openReadStreamPromise(entry), chunks = []; for await (const chunk of stream) chunks.push(chunk); return JSON.parse(Buffer.concat(chunks).toString()) } } finally { zip.close() } throw new Error('missing manifest') }
function packTemps(f) { return readdirSync(f.root).filter((name) => name.startsWith('.out.zip.') && name.endsWith('.tmp')) }
async function rejects(f, pattern) { await assert.rejects(() => pack.run(f.args), pattern); assert.equal(existsSync(f.output), false); assert.deepEqual(packTemps(f), []); rmSync(f.root, { recursive: true, force: true }) }
test('packs app and fixed-point manifest', async () => { const f = fixture(); await pack.run(f.args); const m = await manifest(f.output); assert.equal(m.kind, 'magicpot-app'); assert.equal(m.files[0].sha256, createHash('sha256').update('app').digest('hex')); assert.equal(m.unpackedSize, m.files[0].size + Buffer.byteLength(JSON.stringify(m, null, 2) + '\n')); rmSync(f.root, { recursive: true }) })
test('packs runtime', async () => { const f = fixture('runtime'); await pack.run(f.args); assert.deepEqual((await manifest(f.output)).entrypoints, { python: 'python.exe', comfyui: 'ComfyUI/main.py' }); rmSync(f.root, { recursive: true }) })
test('is deterministic', async () => { const a = fixture(), b = fixture(); await pack.run(a.args); await pack.run(b.args); assert.deepEqual(readFileSync(a.output), readFileSync(b.output)); rmSync(a.root, { recursive: true }); rmSync(b.root, { recursive: true }) })
test('rejects existing output', async () => { const f = fixture(); writeFileSync(f.output, 'x'); await assert.rejects(() => pack.run(f.args), /already exists/); rmSync(f.root, { recursive: true }) })
test('rejects existing manifest', async () => { const f = fixture(); writeFileSync(join(f.input, 'manifest.json'), '{}'); await rejects(f, /manifest/) })
test('rejects missing entrypoint', async () => { const f = fixture(); f.value.entrypoint = 'missing.exe'; writeFileSync(f.identity, JSON.stringify(f.value)); await rejects(f, /entrypoint/) })
test('rejects unknown identity field', async () => { const f = fixture(); f.value.private = true; writeFileSync(f.identity, JSON.stringify(f.value)); await rejects(f, /unknown|private/) })
test('rejects duplicate identity key', async () => { const f = fixture(); writeFileSync(f.identity, JSON.stringify(f.value).replace('{', '{"version":"9.9.9",')); await rejects(f, /duplicate/) })
test('rejects kind mismatch', async () => { const f = fixture(); f.args[1] = 'runtime'; await rejects(f, /identity/) })
test('rejects symlink', async (t) => { const f = fixture(); try { symlinkSync(join(f.input, 'MagicPot.exe'), join(f.input, 'link.exe')); await rejects(f, /symlink/) } catch (e) { rmSync(f.root, { recursive: true, force: true }); t.skip(String(e)) } })
test('rejects hardlink', async () => { const f = fixture(); linkSync(join(f.input, 'MagicPot.exe'), join(f.input, 'copy.exe')); await rejects(f, /hardlink/) })
test('rejects case collision where supported', async (t) => { const f = fixture(); writeFileSync(join(f.input, 'x'), '1'); writeFileSync(join(f.input, 'X'), '2'); if (readFileSync(join(f.input, 'x'), 'utf8') === '2') { rmSync(f.root, { recursive: true }); return t.skip('case-insensitive filesystem') } await rejects(f, /collision/) })
test('detects tamper after scan', async () => { const f = fixture(); pack.__setPackLimitsForTest({ afterScan: () => writeFileSync(join(f.input, 'MagicPot.exe'), 'changed') }); try { await rejects(f, /changed/) } finally { pack.__setPackLimitsForTest() } })
test('simulates ZIP32 overflow', async () => { const f = fixture(); pack.__setPackLimitsForTest({ zipLimit: 100 }); try { await rejects(f, /ZIP32/) } finally { pack.__setPackLimitsForTest() } })
test('rejects invalid DOS timestamp range', async () => { const f = fixture(); f.value.createdAt = '2200-01-01T00:00:00Z'; writeFileSync(f.identity, JSON.stringify(f.value)); await rejects(f, /DOS/) })
test('rejects invalid commit identity', async () => { const f = fixture(); f.value.commitSha = '0'.repeat(40); writeFileSync(f.identity, JSON.stringify(f.value)); await rejects(f, /identity/) })
test('detects nested add after scan', async () => { const f = fixture(); mkdirSync(join(f.input, 'nested')); writeFileSync(join(f.input, 'nested/a'), 'a'); pack.__setPackLimitsForTest({ afterScan: () => writeFileSync(join(f.input, 'nested/new'), 'x') }); try { await rejects(f, /tree changed/) } finally { pack.__setPackLimitsForTest() } })
test('detects nested delete after scan', async () => { const f = fixture(); mkdirSync(join(f.input, 'nested')); writeFileSync(join(f.input, 'nested/a'), 'a'); pack.__setPackLimitsForTest({ afterScan: () => unlinkSync(join(f.input, 'nested/a')) }); try { await rejects(f, /tree changed/) } finally { pack.__setPackLimitsForTest() } })
test('identity path swap cannot be accepted', async () => { const f = fixture(), replacement = join(f.root, 'replacement.json'); writeFileSync(replacement, JSON.stringify(f.value)); pack.__setPackLimitsForTest({ afterIdentityOpen: () => { unlinkSync(f.identity); renameSync(replacement, f.identity) } }); try { await rejects(f, /identity failed safety checks/) } finally { pack.__setPackLimitsForTest() } })
test('output replacement after link never succeeds', async () => { const f = fixture(); pack.__setPackLimitsForTest({ afterLink: (output) => { unlinkSync(output); writeFileSync(output, 'attacker') } }); try { await assert.rejects(() => pack.run(f.args), /published output/); assert.equal(readFileSync(f.output, 'utf8'), 'attacker') } finally { pack.__setPackLimitsForTest(); rmSync(f.root, { recursive: true, force: true }) } })
test('self-validation corruption never succeeds', async () => { const f = fixture(); let corrupted = false; pack.__setPackLimitsForTest({ corruptBeforeVerify: (fd) => { if (!corrupted) { corrupted = true; writeSync(fd, Buffer.from([0]), 0, 1, 0) } } }); try { await assert.rejects(() => pack.run(f.args), /safe ZIP|snapshotting|safety/); assert.equal(existsSync(f.output), false) } finally { pack.__setPackLimitsForTest(); rmSync(f.root, { recursive: true, force: true }) } })
test('pack failure removes its large temporary file', async () => { const f = fixture(); pack.__setPackLimitsForTest({ afterTempOpen: (_temporary, fd) => { const chunk = Buffer.alloc(1024 * 1024, 0x5a); for (let i = 0; i < 8; i++) writeSync(fd, chunk); throw new Error('injected pack failure') } }); try { await assert.rejects(() => pack.run(f.args), /injected pack failure/); assert.equal(existsSync(f.output), false); assert.deepEqual(packTemps(f), []) } finally { pack.__setPackLimitsForTest(); rmSync(f.root, { recursive: true, force: true }) } })
test('cleanup preserves a replacement despite inode churn', async () => { const f = fixture(); let attackerTemporary; pack.__setPackLimitsForTest({ afterTempOpen: () => { throw new Error('injected cleanup failure') }, beforeCleanup: (temporary) => { unlinkSync(temporary); for (let i = 0; i < 256; i++) { const churn = join(f.root, `churn-${i}`); writeFileSync(churn, 'x'); unlinkSync(churn) } writeFileSync(temporary, 'attacker-owned'); attackerTemporary = temporary } }); try { await assert.rejects(() => pack.run(f.args), /injected cleanup failure/); assert.equal(existsSync(f.output), false); assert.equal(readFileSync(attackerTemporary, 'utf8'), 'attacker-owned') } finally { pack.__setPackLimitsForTest(); rmSync(f.root, { recursive: true, force: true }) } })
test('cleanup removes the original temporary after a normal failure', async () => { const f = fixture(); pack.__setPackLimitsForTest({ afterTempOpen: () => { throw new Error('injected normal failure') }, beforeCleanup: (temporary, fd) => { writeSync(fd, Buffer.from('still-open'), 0, 10, 0); assert.equal(existsSync(temporary), true) } }); try { await assert.rejects(() => pack.run(f.args), /injected normal failure/); assert.equal(existsSync(f.output), false); assert.deepEqual(packTemps(f), []) } finally { pack.__setPackLimitsForTest(); rmSync(f.root, { recursive: true, force: true }) } })
