/* eslint-disable @typescript-eslint/explicit-function-return-type */

export const PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_VERSION = 1
export const PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_NAME =
  'project-canvas-large-image-resource-diagnostics'

export const PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS = Object.freeze([
  {
    key: 'firstThumbnailMs',
    reportKey: 'first-thumbnail-ms',
    unit: 'ms',
    kind: 'duration',
    description: 'Time from image import/request to first thumbnail availability.'
  },
  {
    key: 'cacheHitCount',
    reportKey: 'cache-hit-count',
    unit: 'count',
    kind: 'counter',
    description: 'Thumbnail cache hits observed by the benchmark metrics surface.'
  },
  {
    key: 'nativeGeneratedCount',
    reportKey: 'native-generated-count',
    unit: 'count',
    kind: 'counter',
    description: 'Thumbnails generated by the native thumbnail path.'
  },
  {
    key: 'sidecarGeneratedCount',
    reportKey: 'sidecar-generated-count',
    unit: 'count',
    kind: 'counter',
    description: 'Thumbnails generated by the sidecar/cache-generation path.'
  },
  {
    key: 'residentTextureBytes',
    reportKey: 'resident-texture-bytes',
    unit: 'bytes',
    kind: 'gauge',
    description: 'Resident WebGL texture bytes currently retained by Project Canvas.'
  },
  {
    key: 'sourceUpgradeCount',
    reportKey: 'source-upgrade-count',
    unit: 'count',
    kind: 'counter',
    description: 'Source-image upgrade completions observed by the WebGL image layer.'
  },
  {
    key: 'evictionCount',
    reportKey: 'eviction-count',
    unit: 'count',
    kind: 'counter',
    description: 'Texture/resource evictions observed by the large image resource engine.'
  },
  {
    key: 'evictionReasons',
    reportKey: 'eviction-reasons',
    unit: 'reason-counts',
    kind: 'map',
    description: 'Eviction reason counts when exposed by benchmark diagnostics.'
  },
  {
    key: 'lastEvictionReason',
    reportKey: 'last-eviction-reason',
    unit: 'reason',
    kind: 'label',
    description: 'Last eviction reason when only a single reason label is exposed.'
  },
  {
    key: 'objectUrlCount',
    reportKey: 'object-url-count',
    unit: 'count',
    kind: 'gauge',
    description: 'Active blob/object URL count exposed for large image diagnostics.'
  },
  {
    key: 'activeObjectUrlCount',
    reportKey: 'active-object-url-count',
    unit: 'count',
    kind: 'gauge',
    description: 'Active blob/object URL count exposed for leak diagnostics.'
  },
  {
    key: 'revokedObjectUrlCount',
    reportKey: 'revoked-object-url-count',
    unit: 'count',
    kind: 'counter',
    description: 'Blob/object URLs revoked by the resource release path.'
  },
  {
    key: 'closedImageBitmapCount',
    reportKey: 'closed-image-bitmap-count',
    unit: 'count',
    kind: 'counter',
    description: 'ImageBitmap instances closed by the resource release path.'
  },
  {
    key: 'disposedTextureCount',
    reportKey: 'disposed-texture-count',
    unit: 'count',
    kind: 'counter',
    description: 'WebGL/renderer textures disposed by the resource release path.'
  },
  {
    key: 'disposedLeaseCount',
    reportKey: 'disposed-lease-count',
    unit: 'count',
    kind: 'counter',
    description: 'Resource leases disposed by the release path.'
  },
  {
    key: 'releaseErrorCount',
    reportKey: 'release-error-count',
    unit: 'count',
    kind: 'counter',
    description: 'Resource release/disposal errors observed by diagnostics.'
  },
  {
    key: 'residentTextureBudgetBytes',
    reportKey: 'resident-texture-budget-bytes',
    unit: 'bytes',
    kind: 'gauge',
    description: 'Resident WebGL texture byte budget exposed for budget diagnostics.'
  },
  {
    key: 'decodedInFlightBytes',
    reportKey: 'decoded-in-flight-bytes',
    unit: 'bytes',
    kind: 'gauge',
    description: 'Decoded image bytes currently reserved/in flight.'
  },
  {
    key: 'resourceBudgetPressure',
    reportKey: 'resource-budget-pressure',
    unit: 'state',
    kind: 'state',
    description: 'Resource budget pressure state(s) exposed by diagnostics.'
  },
  {
    key: 'sidecarFailedCount',
    reportKey: 'sidecar-failed-count',
    unit: 'count',
    kind: 'counter',
    description: 'Thumbnail sidecar failures observed by diagnostics.'
  }
])

const FIELD_BY_KEY = new Map(
  PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS.map((field) => [field.key, field])
)

function hasOwn(object, key) {
  return Boolean(object && Object.prototype.hasOwnProperty.call(object, key))
}

function readPath(object, pathSegments) {
  let cursor = object
  for (const segment of pathSegments) {
    if (!hasOwn(cursor, segment)) {
      return { found: false, value: undefined }
    }
    cursor = cursor[segment]
  }
  return { found: true, value: cursor }
}

function readFirstPath(paths) {
  for (const { label, root, path } of paths) {
    const candidate = readPath(root, path)
    if (candidate.found) {
      return {
        label: `${label}.${path.join('.')}`,
        value: candidate.value
      }
    }
  }
  return null
}

function parseProjectCanvasMetricsSnapshot(rootDataset = {}) {
  const snapshotText = rootDataset.projectCanvasMetricsSnapshot
  if (!snapshotText) {
    return null
  }

  try {
    const parsed = JSON.parse(snapshotText)
    return parsed && typeof parsed === 'object' ? parsed : null
  } catch {
    return null
  }
}

function toNonNegativeNumber(value) {
  if (value === null || value === undefined || value === '') {
    return null
  }
  const parsed = Number(value)
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : null
}

function readFirstNonNegativeNumber(candidates) {
  for (const candidate of candidates) {
    if (!candidate) {
      continue
    }
    const parsed = toNonNegativeNumber(candidate.value)
    if (parsed !== null) {
      return {
        value: parsed,
        source: candidate.label
      }
    }
  }
  return {
    value: null,
    source: null
  }
}

function normalizeReasonKey(value) {
  const normalized = `${value ?? ''}`.trim()
  return normalized || null
}

function addReasonCount(target, reason, count = 1) {
  const key = normalizeReasonKey(reason)
  const parsedCount = toNonNegativeNumber(count)
  if (!key || parsedCount === null) {
    return
  }
  target[key] = (target[key] || 0) + parsedCount
}

function parseReasonCounts(value) {
  if (value === null || value === undefined || value === '') {
    return null
  }

  if (typeof value === 'string') {
    const trimmed = value.trim()
    if (!trimmed) {
      return null
    }
    try {
      return parseReasonCounts(JSON.parse(trimmed))
    } catch {
      return { [trimmed]: 1 }
    }
  }

  const reasons = {}
  if (Array.isArray(value)) {
    for (const entry of value) {
      if (typeof entry === 'string') {
        addReasonCount(reasons, entry, 1)
        continue
      }
      if (entry && typeof entry === 'object') {
        addReasonCount(
          reasons,
          entry.reason ?? entry.type ?? entry.key ?? entry.name,
          entry.count ?? entry.value ?? 1
        )
      }
    }
    return Object.keys(reasons).length > 0 ? reasons : null
  }

  if (typeof value === 'object') {
    for (const [reason, count] of Object.entries(value)) {
      addReasonCount(reasons, reason, count)
    }
    return Object.keys(reasons).length > 0 ? reasons : null
  }

  return null
}

function readFirstReasonCounts(candidates) {
  for (const candidate of candidates) {
    if (!candidate) {
      continue
    }
    const parsed = parseReasonCounts(candidate.value)
    if (parsed) {
      return {
        value: parsed,
        source: candidate.label
      }
    }
  }
  return {
    value: null,
    source: null
  }
}

function readFirstString(candidates) {
  for (const candidate of candidates) {
    if (!candidate) {
      continue
    }
    const value = normalizeReasonKey(candidate.value)
    if (value) {
      return {
        value,
        source: candidate.label
      }
    }
  }
  return {
    value: null,
    source: null
  }
}

function sumReasonCounts(reasonCounts) {
  if (!reasonCounts) {
    return null
  }
  const total = Object.values(reasonCounts).reduce((sum, value) => {
    const parsed = toNonNegativeNumber(value)
    return parsed === null ? sum : sum + parsed
  }, 0)
  return Number.isFinite(total) ? total : null
}

function buildSources(rootDataset, metricsSnapshot) {
  const snapshot = metricsSnapshot || parseProjectCanvasMetricsSnapshot(rootDataset)
  const thumbnailCache = snapshot?.thumbnailCache || snapshot?.thumbnails || null
  const webgl = snapshot?.webgl || null
  const largeImageResources =
    snapshot?.largeImageResources ||
    snapshot?.largeImageResourceMetrics ||
    snapshot?.imageResources ||
    snapshot?.largeImages ||
    null
  const objectUrls = snapshot?.objectUrls || snapshot?.objectURL || null
  const release =
    snapshot?.release ||
    snapshot?.resourceRelease ||
    snapshot?.resourceReleases ||
    snapshot?.releaseDiagnostics ||
    null
  const resourceBudget =
    snapshot?.resourceBudget ||
    snapshot?.imageResourceBudget ||
    snapshot?.canvasImageResourceBudget ||
    snapshot?.budget ||
    null

  return {
    dataset: rootDataset || {},
    snapshot,
    thumbnailCache,
    webgl,
    largeImageResources,
    objectUrls,
    release,
    resourceBudget
  }
}

function candidate(label, root, path) {
  const found = readFirstPath([{ label, root, path }])
  return found
}

function buildNumberCandidates(sources, paths) {
  return paths.map(([label, root, path]) => candidate(label, root, path)).filter(Boolean)
}

function readNumberMetric(sources, paths) {
  return readFirstNonNegativeNumber(buildNumberCandidates(sources, paths))
}

function readReasonMetric(sources, paths) {
  return readFirstReasonCounts(buildNumberCandidates(sources, paths))
}

function readStringMetric(sources, paths) {
  return readFirstString(buildNumberCandidates(sources, paths))
}

function buildResourceBudgetPressureValue(pressure) {
  if (!pressure || typeof pressure !== 'object') {
    return null
  }
  if (Array.isArray(pressure)) {
    const pressureEntries = pressure
      .map((entry) => normalizeReasonKey(entry?.reason ?? entry?.key ?? entry?.state ?? entry))
      .filter(Boolean)
    return pressureEntries.length > 0 ? pressureEntries.join(',') : null
  }

  const pressuredEntries = Object.entries(pressure)
    .map(([key, state]) => {
      const normalizedState = normalizeReasonKey(state)
      return normalizedState && normalizedState !== 'available' && normalizedState !== 'unbounded'
        ? `${key}:${normalizedState}`
        : null
    })
    .filter(Boolean)
  return pressuredEntries.length > 0 ? pressuredEntries.join(',') : null
}

function buildReportFields(values) {
  return Object.fromEntries(
    PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS.map((field) => [
      field.reportKey,
      values[field.key]
    ])
  )
}

function buildAvailability(values) {
  return Object.fromEntries(
    PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS.map((field) => [
      field.key,
      values[field.key] !== null && values[field.key] !== undefined
    ])
  )
}

function buildSchemaFields() {
  return PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS.map((field) => ({ ...field }))
}

export function collectProjectCanvasLargeImageResourceMetricsFromDomSnapshot(snapshotInput = {}) {
  const rootDataset = snapshotInput.rootDataset || {}
  const sources = buildSources(rootDataset, snapshotInput.metricsSnapshot)
  const values = {}
  const sourceLabels = {}
  const derivedFields = []

  const assignNumber = (key, paths) => {
    const metric = readNumberMetric(sources, paths)
    values[key] = metric.value
    sourceLabels[key] = metric.source
  }

  assignNumber('firstThumbnailMs', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['firstThumbnailMs']],
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['firstThumbnailDurationMs']
    ],
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['firstThumbnailLatencyMs']
    ],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['firstThumbnailMs']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['firstThumbnailDurationMs']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['firstThumbnailLatencyMs']],
    ['dataset', sources.dataset, ['projectCanvasFirstThumbnailMs']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailFirstMs']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailFirstDurationMs']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailCacheFirstThumbnailMs']]
  ])

  assignNumber('cacheHitCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['cacheHitCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['hitCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['cacheHitCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['hitCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['hits']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailCacheHitCount']],
    ['dataset', sources.dataset, ['projectCanvasCacheHitCount']]
  ])

  assignNumber('nativeGeneratedCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['nativeGeneratedCount']],
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['nativeThumbnailGeneratedCount']
    ],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['nativeGeneratedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['nativeThumbnailGeneratedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['nativeGenerated']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailCacheNativeGeneratedCount']],
    ['dataset', sources.dataset, ['projectCanvasNativeThumbnailGeneratedCount']],
    ['dataset', sources.dataset, ['projectCanvasNativeGeneratedCount']]
  ])

  assignNumber('sidecarGeneratedCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['sidecarGeneratedCount']],
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['sidecarThumbnailGeneratedCount']
    ],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['sidecarGeneratedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['sidecarThumbnailGeneratedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['sidecarGenerated']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailCacheSidecarGeneratedCount']],
    ['dataset', sources.dataset, ['projectCanvasSidecarThumbnailGeneratedCount']],
    ['dataset', sources.dataset, ['projectCanvasSidecarGeneratedCount']]
  ])

  assignNumber('residentTextureBytes', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['residentTextureBytes']],
    ['metricsSnapshot.webgl', sources.webgl, ['residentTextureBytes']],
    ['dataset', sources.dataset, ['projectCanvasWebglResidentTextureBytes']],
    ['dataset', sources.dataset, ['projectCanvasResidentTextureBytes']]
  ])

  assignNumber('sourceUpgradeCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['sourceUpgradeCount']],
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['sourceUpgradeCompletedCount']
    ],
    ['metricsSnapshot.webgl', sources.webgl, ['sourceUpgradeCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['sourceUpgradeCompletedCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['sourceUpgradeCompletedImageCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['sourceUpgradedImageCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglSourceUpgradeCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglSourceUpgradeCompletedCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglSourceUpgradeCompletedImageCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglSourceUpgradedImageCount']],
    ['dataset', sources.dataset, ['projectCanvasSourceUpgradeCount']]
  ])

  const evictionReasons = readReasonMetric(sources, [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['evictionReasons']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['evictionReasonCounts']],
    ['metricsSnapshot.webgl', sources.webgl, ['evictionReasons']],
    ['metricsSnapshot.webgl', sources.webgl, ['evictionReasonCounts']],
    ['metricsSnapshot.webgl', sources.webgl, ['textureEvictionReasons']],
    ['dataset', sources.dataset, ['projectCanvasWebglEvictionReasons']],
    ['dataset', sources.dataset, ['projectCanvasWebglEvictionReasonCounts']],
    ['dataset', sources.dataset, ['projectCanvasImageResourceEvictionReasons']]
  ])
  values.evictionReasons = evictionReasons.value
  sourceLabels.evictionReasons = evictionReasons.source

  const evictionCount = readNumberMetric(sources, [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['evictionCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['textureEvictionCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['evictionCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['textureEvictionCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglEvictionCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglTextureEvictionCount']],
    ['dataset', sources.dataset, ['projectCanvasImageResourceEvictionCount']]
  ])
  const derivedEvictionCount = sumReasonCounts(values.evictionReasons)
  values.evictionCount = evictionCount.value ?? derivedEvictionCount
  sourceLabels.evictionCount =
    evictionCount.source ?? (derivedEvictionCount !== null ? 'derived.evictionReasons' : null)
  if (evictionCount.value === null && derivedEvictionCount !== null) {
    derivedFields.push('evictionCount')
  }

  const lastEvictionReason = readStringMetric(sources, [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['lastEvictionReason']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['evictionReason']],
    ['metricsSnapshot.webgl', sources.webgl, ['lastEvictionReason']],
    ['metricsSnapshot.webgl', sources.webgl, ['evictionReason']],
    ['dataset', sources.dataset, ['projectCanvasWebglLastEvictionReason']],
    ['dataset', sources.dataset, ['projectCanvasWebglEvictionReason']],
    ['dataset', sources.dataset, ['projectCanvasImageResourceLastEvictionReason']]
  ])
  values.lastEvictionReason = lastEvictionReason.value
  sourceLabels.lastEvictionReason = lastEvictionReason.source

  assignNumber('objectUrlCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['objectUrlCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['objectURLCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['count']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['objectUrlCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['activeCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['activeObjectUrlCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['objectUrlCount']],
    ['dataset', sources.dataset, ['projectCanvasObjectUrlCount']],
    ['dataset', sources.dataset, ['projectCanvasObjectURLCount']],
    ['dataset', sources.dataset, ['projectCanvasImageObjectUrlCount']]
  ])

  assignNumber('activeObjectUrlCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['activeObjectUrlCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['activeObjectURLCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['objectUrlCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['activeObjectUrlCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['activeObjectURLCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['activeCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['count']],
    ['metricsSnapshot.webgl', sources.webgl, ['activeObjectUrlCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['objectUrlCount']],
    ['dataset', sources.dataset, ['projectCanvasActiveObjectUrlCount']],
    ['dataset', sources.dataset, ['projectCanvasActiveObjectURLCount']],
    ['dataset', sources.dataset, ['projectCanvasObjectUrlCount']],
    ['dataset', sources.dataset, ['projectCanvasObjectURLCount']]
  ])

  assignNumber('revokedObjectUrlCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['revokedObjectUrlCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['revokedObjectURLCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['revokedObjectUrlCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['revokedObjectURLCount']],
    ['metricsSnapshot.objectUrls', sources.objectUrls, ['revokedCount']],
    ['metricsSnapshot.release', sources.release, ['revokedObjectUrlCount']],
    ['metricsSnapshot.release', sources.release, ['revokedObjectURLCount']],
    ['metricsSnapshot.release', sources.release, ['objectUrlRevokedCount']],
    ['metricsSnapshot.release', sources.release, ['objectURLRevokedCount']],
    ['dataset', sources.dataset, ['projectCanvasRevokedObjectUrlCount']],
    ['dataset', sources.dataset, ['projectCanvasRevokedObjectURLCount']],
    ['dataset', sources.dataset, ['projectCanvasObjectUrlRevokedCount']]
  ])

  assignNumber('closedImageBitmapCount', [
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['closedImageBitmapCount']
    ],
    ['metricsSnapshot.release', sources.release, ['closedImageBitmapCount']],
    ['metricsSnapshot.release', sources.release, ['imageBitmapClosedCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['closedImageBitmapCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['imageBitmapClosedCount']],
    ['dataset', sources.dataset, ['projectCanvasClosedImageBitmapCount']],
    ['dataset', sources.dataset, ['projectCanvasImageBitmapClosedCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglClosedImageBitmapCount']]
  ])

  assignNumber('disposedTextureCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['disposedTextureCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['textureDisposedCount']],
    ['metricsSnapshot.release', sources.release, ['disposedTextureCount']],
    ['metricsSnapshot.release', sources.release, ['textureDisposedCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['disposedTextureCount']],
    ['metricsSnapshot.webgl', sources.webgl, ['textureDisposedCount']],
    ['dataset', sources.dataset, ['projectCanvasDisposedTextureCount']],
    ['dataset', sources.dataset, ['projectCanvasTextureDisposedCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglDisposedTextureCount']]
  ])

  assignNumber('disposedLeaseCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['disposedLeaseCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['leaseDisposedCount']],
    ['metricsSnapshot.release', sources.release, ['disposedLeaseCount']],
    ['metricsSnapshot.release', sources.release, ['leaseDisposedCount']],
    ['dataset', sources.dataset, ['projectCanvasDisposedLeaseCount']],
    ['dataset', sources.dataset, ['projectCanvasLeaseDisposedCount']]
  ])

  assignNumber('releaseErrorCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['releaseErrorCount']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['releaseErrors']],
    ['metricsSnapshot.release', sources.release, ['releaseErrorCount']],
    ['metricsSnapshot.release', sources.release, ['errorCount']],
    ['metricsSnapshot.release', sources.release, ['errors']],
    ['metricsSnapshot.webgl', sources.webgl, ['releaseErrorCount']],
    ['dataset', sources.dataset, ['projectCanvasReleaseErrorCount']],
    ['dataset', sources.dataset, ['projectCanvasResourceReleaseErrorCount']],
    ['dataset', sources.dataset, ['projectCanvasWebglReleaseErrorCount']]
  ])

  assignNumber('residentTextureBudgetBytes', [
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['residentTextureBudgetBytes']
    ],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['textureBudgetBytes']],
    ['metricsSnapshot.webgl', sources.webgl, ['residentTextureBudgetBytes']],
    ['metricsSnapshot.webgl', sources.webgl, ['textureBudgetBytes']],
    ['metricsSnapshot.resourceBudget', sources.resourceBudget, ['limits', 'sourceTextureBytes']],
    ['metricsSnapshot.resourceBudget', sources.resourceBudget, ['residentTextureBudgetBytes']],
    ['dataset', sources.dataset, ['projectCanvasWebglResidentTextureBudgetBytes']],
    ['dataset', sources.dataset, ['projectCanvasResidentTextureBudgetBytes']],
    ['dataset', sources.dataset, ['projectCanvasTextureBudgetBytes']]
  ])

  assignNumber('decodedInFlightBytes', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['decodedInFlightBytes']],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['decodeInFlightBytes']],
    ['metricsSnapshot.resourceBudget', sources.resourceBudget, ['usage', 'decodedInFlightBytes']],
    ['metricsSnapshot.resourceBudget', sources.resourceBudget, ['decodedInFlightBytes']],
    ['metricsSnapshot.webgl', sources.webgl, ['decodedInFlightBytes']],
    ['dataset', sources.dataset, ['projectCanvasDecodedInFlightBytes']],
    ['dataset', sources.dataset, ['projectCanvasDecodeInFlightBytes']],
    ['dataset', sources.dataset, ['projectCanvasImageDecodedInFlightBytes']]
  ])

  const resourceBudgetPressure = readStringMetric(sources, [
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['resourceBudgetPressure']
    ],
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['budgetPressure']],
    ['metricsSnapshot.resourceBudget', sources.resourceBudget, ['resourceBudgetPressure']],
    ['metricsSnapshot.resourceBudget', sources.resourceBudget, ['budgetPressure']],
    ['metricsSnapshot.webgl', sources.webgl, ['resourceBudgetPressure']],
    ['dataset', sources.dataset, ['projectCanvasResourceBudgetPressure']],
    ['dataset', sources.dataset, ['projectCanvasImageResourceBudgetPressure']]
  ])
  const derivedResourceBudgetPressure = buildResourceBudgetPressureValue(
    sources.resourceBudget?.pressure
  )
  values.resourceBudgetPressure = resourceBudgetPressure.value ?? derivedResourceBudgetPressure
  sourceLabels.resourceBudgetPressure =
    resourceBudgetPressure.source ??
    (derivedResourceBudgetPressure !== null ? 'derived.resourceBudget.pressure' : null)
  if (resourceBudgetPressure.value === null && derivedResourceBudgetPressure !== null) {
    derivedFields.push('resourceBudgetPressure')
  }

  assignNumber('sidecarFailedCount', [
    ['metricsSnapshot.largeImageResources', sources.largeImageResources, ['sidecarFailedCount']],
    [
      'metricsSnapshot.largeImageResources',
      sources.largeImageResources,
      ['sidecarThumbnailFailedCount']
    ],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['sidecarFailedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['sidecarThumbnailFailedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['cacheFailedCount']],
    ['metricsSnapshot.thumbnailCache', sources.thumbnailCache, ['failedCount']],
    ['dataset', sources.dataset, ['projectCanvasSidecarFailedCount']],
    ['dataset', sources.dataset, ['projectCanvasSidecarThumbnailFailedCount']],
    ['dataset', sources.dataset, ['projectCanvasThumbnailCacheFailedCount']]
  ])

  return {
    schemaName: PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_NAME,
    schemaVersion: PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_VERSION,
    diagnosticOnly: true,
    officialAcceptanceImpact: false,
    thresholdsChanged: false,
    fields: buildReportFields(values),
    values,
    availability: buildAvailability(values),
    sources: sourceLabels,
    derivedFields,
    schema: {
      fields: buildSchemaFields()
    }
  }
}

export function attachProjectCanvasLargeImageResourceDiagnostics(
  metrics,
  largeImageResourceMetrics
) {
  return {
    ...metrics,
    largeImageResourceMetrics,
    diagnosticMetrics: {
      ...(metrics?.diagnosticMetrics || {}),
      largeImageResources: largeImageResourceMetrics
    }
  }
}

function formatMetricValue(key, value) {
  if (value === null || value === undefined) {
    return null
  }
  const field = FIELD_BY_KEY.get(key)
  const reportKey = field?.reportKey || key
  if (typeof value === 'object') {
    return `${reportKey}=${JSON.stringify(value)}`
  }
  const unit = field?.unit
  return `${reportKey}=${value}${unit === 'ms' ? 'ms' : ''}`
}

export function formatProjectCanvasLargeImageResourceMetrics(metrics) {
  const values = metrics?.values || {}
  const parts = PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS.map((field) =>
    formatMetricValue(field.key, values[field.key])
  ).filter(Boolean)

  return parts.length > 0
    ? parts.join(', ')
    : 'no optional large image resource diagnostics observed'
}

export function validateProjectCanvasLargeImageResourceMetrics(metrics) {
  const errors = []
  if (!metrics || typeof metrics !== 'object') {
    return ['metrics must be an object']
  }
  if (metrics.schemaName !== PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_NAME) {
    errors.push(`schemaName must be ${PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_NAME}`)
  }
  if (metrics.schemaVersion !== PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_VERSION) {
    errors.push(
      `schemaVersion must be ${PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRICS_SCHEMA_VERSION}`
    )
  }
  if (metrics.diagnosticOnly !== true) {
    errors.push('diagnosticOnly must be true')
  }
  if (metrics.officialAcceptanceImpact !== false) {
    errors.push('officialAcceptanceImpact must be false')
  }
  if (metrics.thresholdsChanged !== false) {
    errors.push('thresholdsChanged must be false')
  }
  if (!metrics.fields || typeof metrics.fields !== 'object') {
    errors.push('fields must be an object')
  }
  if (!metrics.values || typeof metrics.values !== 'object') {
    errors.push('values must be an object')
  }

  for (const field of PROJECT_CANVAS_LARGE_IMAGE_RESOURCE_METRIC_FIELDS) {
    const value = metrics.values?.[field.key]
    if (value === null || value === undefined) {
      continue
    }
    if (field.kind === 'map') {
      if (!value || typeof value !== 'object' || Array.isArray(value)) {
        errors.push(`${field.key} must be a reason-count object or null`)
      }
      continue
    }
    if (field.kind === 'label' || field.kind === 'state') {
      if (typeof value !== 'string') {
        errors.push(`${field.key} must be a string or null`)
      }
      continue
    }
    if (toNonNegativeNumber(value) === null) {
      errors.push(`${field.key} must be a non-negative number or null`)
    }
  }

  return errors
}
