name: CI On Master

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: {}

jobs:
  ci:
    permissions:
      contents: read
    uses: ./.github/workflows/call-ci.yml
    with:
      ref: ${{ github.ref }}
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/call-build.yml
    with:
      ref: ${{ github.ref }}
